language: python
addons:
  apt_packages:
  - pandoc
python:
- '3.6'
install:
- make bootstrap
script:
- make guide
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: "./_build/html"
env:
  global:
    secure: YxBC6R4luN4m40b/zEWXuovGPrgxLhTWt2i6MtFG23bToILZ0pXZV+N8zcAnyvCRniyzvK73v8wfACX3O5BbW2lBkqk8VL+s7863JQ6aC5PmDgRShO/UsJgttRLfRVRXhk1QKP7PQmZWzDvIVnTOHQUEmCtUc2qBHTZGy+M/9BuVMp8Y0dEg12uXZzj/Z1rOrgTil1j9feEcz9OydzHBYjmcKlivMnvxNXC2xaYSZ7iQxW1ZGRDy2u7b4qa5wRh8s3wmXCpXAy7miOkuAC7IGaUzvQXrTABOjvViZy8zMPUftakd3avAShDwkjrElt4BUWqG2cU8RxOPXd8uAx/nuvQBQHy/ERhABAM4Z5R1Va0XhxIPEw3Mlir0cs0wu/8LMB8lKC3BIGybPoS/exaHmIq+qFwxw4nQDJIhlcI/dRI8Lo0JM/SSQxjWmKDEF9I7qz1l5ijZU38SZEkkXWjs1WVZFwdoZqqC4m0d9iUEpfdlqfUmSXpMbKXMhOemiMd9DCRyKJRdAvuX4AOROlsiiU1KMKEdCc1uGh3LXS/J86z/n+JvhHVK7dX5JJpsXRfVjiY7IzbytaS+yn2wBtOBYysl60P7n7pJ9SrVyQqrAE1rY3sCINc18v77ZVI8QYjk6JsZ7taTXooS4GJAs3ZK0odalvRojroz7yA82XguvpU=
    